export const APP_NAME = 'ProductPilot AI';
export const APP_TAGLINE = 'Find winning products before you spend money.';
export const APP_DESCRIPTION =
  'AI-powered product research, competition analysis, profitability calculations and marketing insights — all in one place.';

export function appUrl() {
  return (process.env.NEXT_PUBLIC_APP_URL ?? process.env.APP_URL ?? 'http://localhost:3000').replace(
    /\/$/,
    '',
  );
}

/**
 * Shown wherever a number is produced by the model rather than measured from a
 * live data source. Used verbatim across the UI and the exported PDF.
 */
export const AI_ESTIMATE_LABEL = 'AI estimate';
export const AI_ESTIMATE_TOOLTIP =
  'Generated by an AI model from the product information you provided. It is an opinion, not a measured market statistic.';
export const LIVE_DATA_UNAVAILABLE_LABEL = 'Live data unavailable';
