import type { Metadata } from 'next';
import Link from 'next/link';
import { PageHeader } from '@/components/dashboard/topbar';
import {
  AppearanceSettings,
  EmailVerification,
  PasswordForm,
  ProfileForm,
} from '@/components/dashboard/settings-forms';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { requireUser } from '@/lib/auth/current-user';
import { PLANS } from '@/lib/plans';
import { isDemoMode } from '@/lib/ai';
import { dataSourceStatuses } from '@/lib/data-providers';
import { formatDate } from '@/lib/utils';

export const metadata: Metadata = { title: 'Settings' };

export default async function SettingsPage() {
  const user = await requireUser();
  const plan = PLANS[user.plan];
  const demoMode = isDemoMode();
  const sources = dataSourceStatuses();

  return (
    <>
      <PageHeader title="Settings" description="Your profile, security and workspace preferences." />

      <div className="grid gap-5 lg:grid-cols-2 lg:items-start">
        <div className="space-y-5">
          <ProfileForm name={user.name} avatarUrl={user.avatarUrl} />
          <EmailVerification verified={user.emailVerified} email={user.email} />
          <AppearanceSettings />
        </div>

        <div className="space-y-5">
          <PasswordForm />

          <Card>
            <CardHeader>
              <CardTitle>Plan and usage</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between gap-3">
                <span className="text-sm text-fg-muted">Current plan</span>
                <Badge variant={user.plan === 'FREE' ? 'neutral' : 'brand'}>{plan.name}</Badge>
              </div>
              <div className="flex items-center justify-between gap-3">
                <span className="text-sm text-fg-muted">Analyses this period</span>
                <span className="text-sm font-medium tabular-nums">
                  {user.entitlements.analysesUsed} / {user.entitlements.analysesLimit}
                </span>
              </div>
              <div className="flex items-center justify-between gap-3">
                <span className="text-sm text-fg-muted">AI credits remaining</span>
                <span className="text-sm font-medium tabular-nums">{user.entitlements.creditsRemaining}</span>
              </div>
              <div className="flex items-center justify-between gap-3">
                <span className="text-sm text-fg-muted">Period ends</span>
                <span className="text-sm font-medium">{formatDate(user.entitlements.period.end)}</span>
              </div>
              <div className="flex items-center justify-between gap-3">
                <span className="text-sm text-fg-muted">Member since</span>
                <span className="text-sm font-medium">{formatDate(user.createdAt)}</span>
              </div>
              <Button asChild variant="secondary" className="w-full">
                <Link href="/dashboard/billing">Manage plan</Link>
              </Button>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>AI and data sources</CardTitle>
              <p className="mt-1 text-sm text-fg-muted">What this workspace is actually connected to.</p>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="text-sm font-medium">AI provider</p>
                  <p className="mt-0.5 text-xs leading-relaxed text-fg-muted">
                    {demoMode
                      ? 'No provider key is configured, so generated content is clearly-labelled sample output.'
                      : 'A provider key is configured. Analyses are generated by the configured model.'}
                  </p>
                </div>
                <Badge variant={demoMode ? 'potential' : 'strong'}>{demoMode ? 'Demo mode' : 'Connected'}</Badge>
              </div>

              {sources.map((source) => (
                <div key={source.label} className="flex items-start justify-between gap-3">
                  <div>
                    <p className="text-sm font-medium">{source.label}</p>
                    <p className="mt-0.5 text-xs leading-relaxed text-fg-muted">{source.reason}</p>
                  </div>
                  <Badge variant={source.available ? 'strong' : 'neutral'}>
                    {source.available ? 'Connected' : 'Unavailable'}
                  </Badge>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </>
  );
}
